### ISSUE TITLE
Proper Shebang 

### ISSUE THREAD

**Issue by Izder456** [q60/disfetch#12]
the current shebang `#!/bin/sh`, does not properly display the ascii art
change to `#!/bin/bash` to fix this issue, 
for some distros that store bash in a weird spot like alpine's `/usr/bin/bash`, have auto detect in the `Makefile` change the shebang per system

**Comment by q60** [comment]
won't be changed because disfetch is a POSIX Shell tool. `sh` executable is always at the `/bin/`, the only problem is that some distros may use `dash` instead... then it has `/bin/sh` symbolic link. it is an issue to work with.
by the way, you don't have to change your shebang, you can simply do `#!/bin/env bash`.
